/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.systemengineering.tp1paradigmaylenguajesdeprogramacionii.views;

import com.systemengineering.tp1paradigmaylenguajesdeprogramacionii.controllers.MenuController;

/**
 *
 * @author José Fernando Usui y Luciana Rojas
 */
public class MenuView extends javax.swing.JFrame {

    private final MenuController menuController;

    /**
     * Creates new form Menu
     *
     * @param menuController
     */
    public MenuView(MenuController menuController) {
        this.menuController = menuController;
        initComponents();
    }

    public javax.swing.ImageIcon obtenerImagenUniversidad() {
        try {
            java.awt.image.BufferedImage originalImage = javax.imageio.ImageIO.read(
                    MenuView.class.getResourceAsStream("images/universidad.png")
            );
            java.awt.Image resizedImage = originalImage.getScaledInstance(500, 170, java.awt.Image.SCALE_SMOOTH);
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(resizedImage);
            return icon;
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnMatricular = new javax.swing.JButton();
        buttonPanel2 = new javax.swing.JPanel();
        btnInscribir = new javax.swing.JButton();
        buttonPanel3 = new javax.swing.JPanel();
        btnSituacionMateria = new javax.swing.JButton();
        buttonPanel4 = new javax.swing.JPanel();
        btnVerAlumnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBounds(new java.awt.Rectangle(50, 50, 800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setAutoscrolls(true);
        jPanelMenu.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(obtenerImagenUniversidad());
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(60, 40, 50, 40);
        jPanelMenu.add(jLabel1, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.BorderLayout());

        btnMatricular.setBackground(new java.awt.Color(102, 102, 102));
        btnMatricular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMatricular.setText("Matricular Alumnos a una Carrera");
        btnMatricular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatricularMouseClicked(evt);
            }
        });
        buttonPanel.add(btnMatricular, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanelMenu.add(buttonPanel, gridBagConstraints);

        buttonPanel2.setLayout(new java.awt.BorderLayout());

        btnInscribir.setBackground(new java.awt.Color(102, 102, 102));
        btnInscribir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInscribir.setText("Inscribir Alumno a una Materia");
        btnInscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInscribirMouseClicked(evt);
            }
        });
        buttonPanel2.add(btnInscribir, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanelMenu.add(buttonPanel2, gridBagConstraints);

        buttonPanel3.setLayout(new java.awt.BorderLayout());

        btnSituacionMateria.setBackground(new java.awt.Color(102, 102, 102));
        btnSituacionMateria.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSituacionMateria.setText("Cargar Situacion Final de Materia");
        btnSituacionMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSituacionMateriaMouseClicked(evt);
            }
        });
        buttonPanel3.add(btnSituacionMateria, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanelMenu.add(buttonPanel3, gridBagConstraints);

        buttonPanel4.setLayout(new java.awt.BorderLayout());

        btnVerAlumnos.setBackground(new java.awt.Color(102, 102, 102));
        btnVerAlumnos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVerAlumnos.setText("Ver Alumnos (Segun carrera y materia)");
        btnVerAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerAlumnosMouseClicked(evt);
            }
        });
        buttonPanel4.add(btnVerAlumnos, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 5);
        jPanelMenu.add(buttonPanel4, gridBagConstraints);

        jScrollPane1.setViewportView(jPanelMenu);

        getContentPane().add(jScrollPane1);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatricularMouseClicked
        // TODO add your handling code here:
        menuController.matricular();
    }//GEN-LAST:event_btnMatricularMouseClicked

    private void btnInscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscribirMouseClicked
        // TODO add your handling code here:
        menuController.inscribirse();
    }//GEN-LAST:event_btnInscribirMouseClicked

    private void btnSituacionMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSituacionMateriaMouseClicked
        // TODO add your handling code here:
        menuController.cargarSituacionFinal();
    }//GEN-LAST:event_btnSituacionMateriaMouseClicked

    private void btnVerAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerAlumnosMouseClicked
        // TODO add your handling code here:
        menuController.listarAlumnos();
    }//GEN-LAST:event_btnVerAlumnosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuView(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnSituacionMateria;
    private javax.swing.JButton btnVerAlumnos;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JPanel buttonPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
